name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. ソースコードを取得
      - uses: actions/checkout@v4

      # 2. Python をセットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. pytest 実行
      - name: Run pytest
        run: pytest
